suboptimal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('webapp.urls', namespace='webapp')),

]

webapp/urls.py
from django.conf.urls import url
from django.urls import path

from webapp.views import *

app_name = "webapp"
urlpatterns = [
    path(r'', FrontPage.as_view(), name='front_page'),
    path('wordcloud/<str:subreddit_name>/', WordCloudImageView.as_view(), name='word_cloud'),

]

webapp/models.py
from django.db import models

# Create your models here.
# take the input

webapp/forms.py
from django import forms

from webapp.models import *


class SimilarSubredditForm(forms.Form):
    subreddit = forms.CharField(max_length=40, label="Subreddit")
    num_similar = forms.IntegerField(initial=10, min_value=1, required=True, label="Number of recommendations")

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from PIL import Image
from io import BytesIO

from django.views.generic import *
from webapp.forms import *

from bokeh.plotting import figure, output_file, show
from bokeh.embed import components
from bokeh.models import LabelSet, ColumnDataSource

from sklearn.manifold import TSNE

from recommendations import *

from wordcloud import WordCloud
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

# Treat these as global variables, do not want to reload them each time
embedding_matrix = get_embedding()
id_by_subreddit, subreddit_by_id = get_subreddit_dicts()
text_dict = load_subreddit_text()


class FrontPage(View):
    frontpage_template_name = "front_page.html"
    recommendation_template_name = "subreddit_recommendation.html"

    def get(self, request, *args, **kwargs):
        context = {'form': SimilarSubredditForm()}
        return render(request, self.frontpage_template_name, context)

    def post(self, request, *args, **kwargs):
        form = SimilarSubredditForm(request.POST)
        context = {'form': SimilarSubredditForm()}
        if not form.is_valid():
            return render(request, self.frontpage_template_name, context)
        subreddit = form.cleaned_data["subreddit"]

        # do real work to get recommendations
        if subreddit not in id_by_subreddit.keys():
            # Can't predict for unseen reddit
            messages.error(request, "This subreddit is not in the records.")
            return render(request, self.frontpage_template_name, context)

        recommended_subreddits, not_recommended = recommendations(subreddit, form.cleaned_data["num_similar"],
                                                 embedding_matrix, id_by_subreddit, subreddit_by_id)

        # list of recommended subreddits here
        context["subreddit"] = subreddit
        context["recommended_subreddits"] = recommended_subreddits
        context["not_recommended_subreddits"] = not_recommended

        # tsne plot here
        both_subreddits = recommended_subreddits + not_recommended
        script, div = tsnePlot(both_subreddits)
        context["tsne_script"] = script
        context["tsne_div"] = div

        # word cloud for the input subreddit here
        if subreddit in text_dict:
            # check to see if the dictionary has the subreddit
            context["wordcloud_present"] = True
        else:
            context["wordcloud_present"] = False

        return render(request, self.recommendation_template_name, context)


class WordCloudImageView(View):
    def get(self, request, *args, **kwargs):
        subreddit = kwargs["subreddit_name"]
        text = ''.join(text_dict[subreddit])

        # Generate a word cloud image
        wordcloud = WordCloud().generate(text)

        # Render the matplotlib image from wordcloud to a BytesIO buffer,
        # then return the contents of the buffer.
        plt.imshow(wordcloud, interpolation='bilinear')
        plt.axis("off")
        fig = plt.gcf()

        # Save it to a temporary buffer.
        buffer = BytesIO()
        fig.savefig(buffer, format="png")
        return HttpResponse(buffer.getvalue(), content_type="Image/png")


def tsnePlot(subreddit_names):
    # Returns two components, a script of the plot and the div element
    X = subreddit_embeddings(subreddit_names, embedding_matrix, id_by_subreddit)

    plot = figure(plot_width=400, plot_height=400)

    tsne = TSNE(n_components=2, random_state=0)
    X_tsne = tsne.fit_transform(X)
    X_tsne = X_tsne[:len(subreddit_names), :]

    source = ColumnDataSource(data=dict(tsne_x= X_tsne[:, 0],
                                        tsne_y= X_tsne[:, 1],
                                        subreddit_names=subreddit_names))

    n = int(len(subreddit_names)/2)
    # add a circle renderer with a size, color, and alpha
    plot.circle(x=X_tsne[:n, 0], y=X_tsne[:n, 1], size=20, color="navy", alpha=0.5)
    plot.circle(x=X_tsne[n:, 0], y=X_tsne[n:, 1], size=20, color="red", alpha=0.5)

    labels = LabelSet(x='tsne_x', y='tsne_y', text='subreddit_names', level='glyph', x_offset=5, y_offset=5,
                      source=source)
    plot.add_layout(labels)

    return components(plot)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="https://use.fontawesome.com/releases/v5.0.3/css/all.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.css" type="text/css" />
    <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.css" type="text/css" />
{#    <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.css" type="text/css" />#}

    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.js"></script>
{#    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.js"></script>#}
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-1.2.0.min.js"></script>


    {% block head %}

    {% endblock %}

    <title>{% block title %}Title placeholder{% endblock %}</title>
</head>


<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'webapp:front_page' %}">Front Page</a></li>
        </ul>
    </div>
</nav>


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<div id="content" style="margin-top: 30px;">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

templates/bokeh_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bokeh Scatter Plots</title>
{#   <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css" type="text/css" />#}

    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.css" type="text/css" />
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.css" type="text/css" />
{#    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.css" type="text/css" />#}

    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.js"></script>
{#    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.js"></script>#}
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-api-1.2.0.min.js"></script>

 </head>
 <body>
    Script: {{ tsne_script | safe }}

    Div: {{ tsne_div | safe }}
</body>
{#    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js"></script>#}

</html>

templates/front_page.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Suboptimal{% endblock %}

{% block content %}


    <div class="container-fluid">
        <div class="page-header">
            <h1>Subreddit recommendations</h1>
        </div>

        <br />

        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Enter a subreddit</h5>
                    </div>
                    <div class="card-body">
                        <form method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}

                            {% bootstrap_form form layout="horizontal" %}
                            <div class="float-right">
                                {% buttons %}
                                    <button type="submit" class="btn btn-primary">Save</button>
                                {% endbuttons %}
                            </div>

                        </form>
                        For example:
                        <ul>
                            <li>aww</li>
                            <li>DnD</li>
                            <li>GifRecipes</li>
                            <li>askscience</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>



    </div>

{% endblock %}

templates/subreddit_recommendation.html
{% extends "base.html" %}

{% block title %}Suboptimal{% endblock %}

{% block head %}
    {{ tsne_script | safe }}
{% endblock %}


{% block content %}

    <div class="container-fluid">
        <div class="page-header">
            <h1>Subreddit recommendations for {{ subreddit }}</h1>
        </div>

        <br />

        <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            Most similar
                        </div>
                        <div class="card-body">
                            <ul>
                            {% for s in recommended_subreddits %}
                                <li>{{ s }}</li>
                            {% endfor %}
                            </ul>
                        </div>

                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            Least similar
                        </div>
                        <div class="card-body">
                            <ul>
                            {% for s in not_recommended_subreddits %}
                                <li>{{ s }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
        </div>


        <br />

        <div class="row">
            <div class="col">
                {% if wordcloud_present %}
                    <img src="{% url 'webapp:word_cloud' subreddit %}">
                {% else %}
                    Subreddit text unavailable at this time.
                {% endif %}
            </div>
            <div class="col">
                <div class="embed-wrapper">
                {{ tsne_div | safe }}
                </div>
            </div>
        </div>

    </div>

{% endblock %}